### ISSUE TITLE
Issue with setup in chapter 2

### ISSUE THREAD

**Issue by thebotmakes** [bksarthak/devsecops-book#5]
I get the following error when I'm trying to run the code to set up the stack in chapter 2:

Logical ID: Product

Status: Create failed

Status reason: Invalid templateBody. Please make sure that your template is valid (Service: AWSServiceCatalog; Status Code: 400; Error Code: InvalidParametersException; Request ID: 8932748f-eab6-4abc-a7b2-706ce98a5a7a; Proxy: null)

**Comment by 8carroll** [comment]
I don't think this was in the book, but you need to create an S3 bucket in the account you are using.  Call it eksportfolioproducts, upload eks_provision.yml from the template folder, and run it again.  You've probably moved on, but it works this way.

**Comment by maxrat64** [comment]
Hi, not sure if I'll get any useful information here but I am having the same error that was mentioned above. To my understanding, the `Default` URL (https://s3.amazonaws.com/) provided as a parameter for `ArtifactLoadTemplateFromUrl` is incorrect and needs to be updated by the reader. I have stored the `eks_provision.yml` file provided in the repo and mentioned by @8carroll in an s3 bucket, and now I supply that as the URL in the aforementioned parameter. I am still encountering this issue. 

It is honestly quite frustrating to be running into this problem on the first step of CloudFormation deployment - this is the first AWS API call that is made and it appears to be incorrect. The book features very little introduction or summary of the resources being deployed, and there is no documentation present in this repository in the form of READMEs or even code comments. I'm not brand new to AWS, and I have familiarity with Docker and Kubernetes as well yet I am struggling to make sense of this issue. 

@bksarthak  @virginiachu

**Comment by thebotmakes** [comment]
So I eventually got this working .  Was a while ago now but from memory what I had to do was update ANY parameter where there was a bucket reference in the code, it wasn’t just a one off.  So in all the json files I think I had to change the reference like "https://s3.amazonaws.com/eksportfolioproducts/eks_lambda_vpc.yml" or whatever to whatever my bucket was called.

**Comment by maxrat64** [comment]
Great, thanks! I'll give that a shot.

**Comment by Obasoro** [comment]
@maxrat64 

```An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [ssm:DEV-eks-portfolio-id-us-east-1:1] cannot be found.```

Did you experience this error when running ```aws cloudformation create-stack \
--template-body file://template/ServiceCatalogProduct.yml \
--stack-name EKSNetwork \
--parameters file://parameter/NetworkProduct.json \
--region us-east-1```
